apiVersion: v1
kind: Service
metadata:
  name: snowglobe-web-app
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
    - name: https
      port: 443
      targetPort: 5001
      protocol: TCP
  selector:
    component: sg-web
    type: main
